
# Project Configuration File
title: Eyewear Classification Project_*Hamza

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

# Project-specific directories
assets_dir: assets
data_dir: assets/data
images_dir: assets/images
scripts_dir: assets/scripts
models_dir: assets/models
app_dir: assets/app

show_downloads: True
